# Chat prefix used for all messages in the chat, also changes the greeting messages.
chatPrefix:
  - '[darkgreen][RCRegions][reset]'
  - '  hover: RCRegions region management plugin'
  - '  hover: %lang:action|Click to check the available commands|%'
  - '  command: /rcregions help'
  - ' '
# The language file that should be used, check the 'lang' folder for build-in languages (use the filename without .yml here).
# More information can be found here: https://github.com/NLthijs48/AreaShop/wiki/Language-support.
language: EN
# the relative path where we should load skill configs from
region-groups-path: region-groups
database:
  driver: 'h2'
  url: 'jdbc:h2:~/skills.db'
  username: sa
  password: sa